### ISSUE TITLE
Comments -  close comments after X days and/or Akismet

### ISSUE THREAD

**Issue by chessgriffin** [obfuscurity/blogsum#1]
First, Blogsum is really great software.  Thanks for creating and maintaining the project.  I have tried many of the 'simple' blog engines -- blosxom, py-blosxom, Chronicle, Ode, Flatpress etc -- and none of them are as simple or as nice as Blogsum.

It seems to me that Recaptcha is broken, unfortunately, and I've gotten lots and lots of spam at my Blogsum blog, which has caused me to move away temporarily but I really want to go back to Blogsum.  So, would you consider: (i) adding a feature to 'close' comments after X days to reduce the number of blog posts that might be susceptible to spam and/or (ii) changing the spam countermeasure from Recaptcha to Akismet.  There is an open API for Akismet and a Perl module at CPAN.  Ideally, both would be great but I imagine (i) would be easier to implement than (ii) [although maybe not].

Thanks again for Blogsum!

**Comment by obfuscurity** [comment]
I'm very much against the idea of automatically closing comments. If there's a temporary mailserver issue and the moderator notification is lost, the blog owner might never see the pending comment. I'd rather address the symptom (too much spam). I haven't heard of anyone breaking reCaptcha with automated spam. Are you certain these aren't submitted by humans?

**Comment by obfuscurity** [comment]
Reading up on Akismet, it doesn't look like a great fit for Blogsum. It relies on learning and bayesian-style filters, which I've never been impressed with. Sounds like the Vipul's Razor of comment filters.

**Comment by chessgriffin** [comment]
I just thought adding a tunable option to automatically turn off comments after a certain number of days would give folks a choice -- I wasn't suggesting making it mandatory.  ;-)  As to Akismet, I agree with you in general on bayesian-style filters -- they don't seem to work very well - but Akismet does a great job.  Probably since it's the default anti-spam tool for Wordpress (both self-hosted and their managed blogs at wordpress.com).  I manage some Wordpress blogs and Akismet catches tons of spam with a very high success rate.

In any event, thanks for considering the suggestions, Jason!
